

Vagrant.configure(2) do |config|
  
  unless Vagrant.has_plugin?("vagrant-reload")
    abort 'Plugin needed: vagrant-reload. Run the following command to install: vagrant plugin install vagrant-reload'
  end
  
  config.vm.box = "modernIE/w7-ie11"
  
  config.vm.hostname = "FSE-2012-SANDO"
  
  config.vm.guest=:windows

  # using winrm instead of SSH because it is a windows machine
  config.vm.communicator="winrm"
  
  
   #install copy-files
   config.vm.provision :shell, path: "scripts/copy-files.ps1"
   #install dot-net-4.5
   config.vm.provision :shell, path: "scripts/install-visual-studio.bat"
   #install SANDO
   config.vm.provision :shell, path: "scripts/install-Sando.bat"

   #set startup programs
   config.vm.provision :shell, path: "scripts/copy-startup.bat"
   
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
  #   # Customize the amount of memory on the VM:
  vb.memory = "2048"
  vb.name = "FSE-2012-SANDO"  
  end
  #
  
   
   config.vm.provision :reload
end
